services:
  - docker

language: python

env:
  - DOCKER_COMPOSE_VERSION=1.24.1 DOCKER_USERNAME=panslava

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - pip3 install requests

script:
  - make test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t http_server .
  - docker images
  - docker tag http_server $DOCKER_USERNAME/http_server
  - docker push $DOCKER_USERNAME/http_server

